import type { Metadata } from 'next';
import { Geist_Mono, Manrope } from 'next/font/google';
import Header from '@/components/layout/header/Header';
import Footer from '@/components/layout/footer/Footer';
import './globals.css';
import { FrontEndProvider } from '@/providers/frontend-provider';
import { getHeaderMenus } from '@/lib/db/menus/queries';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menusResponse = await getHeaderMenus();
  const menus = menusResponse.success ? menusResponse.data : undefined;

  return (
    <html lang="en">
      <body className={`${manrope.variable} ${geistMono.variable} antialiased`}>
        <FrontEndProvider>
          <Header menus={menus ?? undefined} />
          <main>{children}</main>
          <Footer />
        </FrontEndProvider>
      </body>
    </html>
  );
}
