/**
 * Mortgage Calculator Constants
 */

export const MORTGAGE_CONSTANTS = {
  DEFAULT_INTEREST_RATE: 4.5,
  MIN_LOAN_TERM: 5,
  MAX_LOAN_TERM: 25,
  MIN_PROPERTY_VALUE: 200000,
  MAX_PROPERTY_VALUE: 50000000,
  MIN_DOWN_PAYMENT: 5,
  MAX_DOWN_PAYMENT: 80,
  DEFAULT_DOWN_PAYMENT_UAE: 20,
  DEFAULT_DOWN_PAYMENT_NON_UAE: 25,
} as const;
