-- ============================================
-- User Roles RBAC Migration
-- ============================================

-- 1. Create role enum type
create type public.app_role as enum ('admin', 'agent', 'customer');

-- 2. Create user_roles table
create table public.user_roles (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users on delete cascade not null,
  role       public.app_role not null default 'customer',
  created_at timestamptz default now(),
  constraint user_roles_user_id_key unique (user_id)
);

comment on table public.user_roles is 'Application roles for each user.';

-- 3. Enable RLS
alter table public.user_roles enable row level security;

-- 4. Create trigger function to auto-assign roles
create or replace function public.handle_new_user_role()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.user_roles (user_id, role)
  values (
    NEW.id,
    case
      when not exists (select 1 from public.user_roles) then 'admin'
      else 'customer'
    end
  );
  return NEW;
end;
$$;

-- 5. Create trigger on auth.users
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user_role();

-- 6. Create custom access token hook to inject role into JWT
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  claims    jsonb;
  user_role public.app_role;
begin
  -- Fetch user role
  select role into user_role
  from public.user_roles
  where user_id = (event->>'user_id')::uuid;

  claims := event->'claims';

  -- Inject role into claims
  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  else
    claims := jsonb_set(claims, '{user_role}', '"customer"');
  end if;

  -- Update event with new claims
  event := jsonb_set(event, '{claims}', claims);

  return event;
end;
$$;

-- 7. Grant permissions for auth hook
grant usage on schema public to supabase_auth_admin;

grant execute
  on function public.custom_access_token_hook
  to supabase_auth_admin;

revoke execute
  on function public.custom_access_token_hook
  from authenticated, anon, public;

grant all
  on table public.user_roles
  to supabase_auth_admin;

revoke all
  on table public.user_roles
  from authenticated, anon, public;

-- 8. Policy for auth admin to read user roles
create policy "Auth admin can read user roles"
  on public.user_roles
  as permissive for select
  to supabase_auth_admin
  using (true);

-- 9. RLS helper function
create or replace function public.has_role(required_role public.app_role)
returns boolean
language plpgsql
stable
security definer set search_path = ''
as $$
declare
  current_role public.app_role;
begin
  select (auth.jwt() ->> 'user_role')::public.app_role
  into current_role;

  return current_role = required_role;
end;
$$;
